version: '3'
services:
  cloudmacs:
    image: karlicoss/cloudmacs:latest
    container_name: cloudmacs
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7001:8080
    environment:
      # ugh. docker-compose can't into proper shell substitution...
      - UNAME
      - GNAME
      - EMACS_UID
      - EMACS_GID
      - UHOME=/home/emacs
    volumes:
      - ${HOME}/.spacemacs.d:/home/emacs/.spacemacs.d
      # TODO document? or add git clone?
      - /L/tmp/cloudmacs/.emacs.d:/home/emacs/.emacs.d
      # add yor org-mode paths here, e.g.
      - ${HOME}/data:/home/emacs/data

