version: '3'
services:
  cloudmacs:
    image: karlicoss/cloudmacs:latest
    container_name: cloudmacs
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    environment:
      # ugh. docker-compose can't into proper shell substitution...
      - UNAME
      - GNAME
      - EMACS_UID
      - EMACS_GID
      - UHOME=/home/emacs
      - TERM=xterm-256color # TODO move it to container instead?
    volumes:
      # you might want to share your emacs/spacemacs init file, normally there should be no harm in it
      - ${HOME}/.spacemacs.d:/home/emacs/.spacemacs.d
      # see Readme::Setting up Spacemacs for explanation
      - ${HOME}/.cloudmacs.d:/home/emacs/.emacs.d
      # map your personal files here you want to make accessible to cloudmacs
      - ${HOME}/data:/home/emacs/data

